const MAX_ITEMS_PER_REQUEST: number = 40
const GOOGLE_BOOKS_API_KEY: string = 'AIzaSyD-2SYYVG-vCeLhk5x0c0PxtPONd8twS_M'
const MAX_DESCRIPTION_LENGTH: number = 100

export { MAX_ITEMS_PER_REQUEST, GOOGLE_BOOKS_API_KEY, MAX_DESCRIPTION_LENGTH }
